// Reading Room IA v2 R3 — the relation authority's runtime layer (frozen R3 plan §8).
//
// data/internal/r3/relations.json is the ONE relation registry (generated by scripts/build-r3-identity.ts from the
// frozen resolved manifest). Every record carries the R3 stage that introduces it and a `state`: only `active` records
// ever reach a page. Nothing here copies a relation into a LibraryWork or LibraryCollection; the reverse indexes below
// are derived on demand.
//
// R3-A: exactly the two relations that were live before R3 are active (Anna and Thennan, rendered through the
// generated POETRY_WITNESS_RELATIONS view in data/poems.ts); the other 47 are dormant.
import identityJson from "../data/internal/r3/identity-manifest.json";
import relationsJson from "../data/internal/r3/relations.json";

export type R3Stage = "R3-A" | "R3-B" | "R3-C" | "R3-D";
export type RelationClass = "source-publication" | "merged-witness" | "commentary-section" | "external-publication";
export type RelationLevel = "work" | "section" | "chapter" | "publication";

export interface WorkRelation {
  id: string;
  class: RelationClass;
  relation: string;
  level: RelationLevel;
  canonicalId: string;
  canonicalSection?: { ordinal: number; titleTa?: string; route?: string };
  witness: { kind: string; locator: string | null } & Record<string, unknown>;
  evidence: Record<string, unknown>;
  introducedIn: R3Stage | "live-pre-R3";
  state: "active" | "dormant";
  publicNote?: { ta: string; en: string };
  legacyPoetryView?: boolean;
}

export interface R3Work {
  id: string;
  titleTa: string;
  titleEn: string;
  shelf: string;
  subtype: string;
  family: string;
  parentPublicationId: string;
  locator: { route: string; fragment: string | null; href: string };
  introducedIn: R3Stage;
  state: "published" | "dormant";
}

export interface R3PublicationUnit {
  unit: string;
  locator: string;
  role: "canonical" | "witness" | "dependent-heading";
  canonicalId: string | null;
  manifestKey: string;
}

export interface R3Publication {
  id: string;
  formerShelf: string;
  href: string;
  demotedIn: R3Stage;
  state: "canonical-until-demotion" | "demoted";
  roleCounts: Record<string, number>;
  units: R3PublicationUnit[];
}

/** Every relation record, active and dormant. */
export const R3_RELATIONS: readonly WorkRelation[] = (relationsJson as { relations: WorkRelation[] }).relations;
/** The generated identity manifest (CREATE identities, publication unit roles, stage state). */
export const R3_IDENTITY = identityJson as unknown as {
  stageState: { order: R3Stage[]; published: R3Stage[] };
  census: Record<string, unknown>;
  works: R3Work[];
  publications: R3Publication[];
};

/** Only these relations may render. Pure over its input so validators can test other states. */
export function activeRelations(relations: readonly WorkRelation[] = R3_RELATIONS): WorkRelation[] {
  return relations.filter((r) => r.state === "active");
}

/** Active witnesses of a canonical work, in registry order. */
export function witnessesOf(canonicalId: string, relations: readonly WorkRelation[] = R3_RELATIONS): WorkRelation[] {
  return activeRelations(relations).filter((r) => r.canonicalId === canonicalId);
}

/** The canonical work an active witness locator (route, optionally `#fragment`) belongs to, if any. */
export function canonicalFor(locator: string, relations: readonly WorkRelation[] = R3_RELATIONS): string | undefined {
  return activeRelations(relations).find((r) => r.witness.locator === locator)?.canonicalId;
}

/**
 * A publication's units with their resolved roles, in printed order. A unit's canonical/witness target is reported
 * only when that identity or relation is live; otherwise the unit is reported as it is today (a unit of a publication
 * that is still a canonical work).
 */
export function publicationAppearances(publicationId: string): { unit: string; locator: string; role: R3PublicationUnit["role"]; canonicalId: string | null; live: boolean }[] {
  const pub = R3_IDENTITY.publications.find((p) => p.id === publicationId);
  if (!pub) return [];
  const published = new Set(R3_IDENTITY.works.filter((w) => w.state === "published").map((w) => w.id));
  const activeWitness = new Set(activeRelations().map((r) => r.witness.locator));
  return pub.units.map((u) => ({
    unit: u.unit,
    locator: u.locator,
    role: u.role,
    canonicalId: u.canonicalId,
    live: u.role === "canonical" ? published.has(u.canonicalId ?? "") : u.role === "witness" ? activeWitness.has(u.locator) : false,
  }));
}

/** The active `merged-witness` record for a former LibraryWork id (none is active before R3-D). */
export function activeMergedWitness(workId: string, relations: readonly WorkRelation[] = R3_RELATIONS): WorkRelation | undefined {
  return activeRelations(relations).find(
    (r) => r.class === "merged-witness" && (r.witness.record as { id?: string } | undefined)?.id === workId,
  );
}
