// Manohara (மனோகரா) — Kalaignar M. Karunanidhi's screenplay/dialogue booklet (1954).
//
// Digital Library Phase 2. Onboarded onto the shared library envelope with its own
// `scene` reader. Data-driven like the other Reading Rooms: the segment index is
// loaded from public/data/cinema/manohara/index.json, per-segment content is fetched
// from public/data/cinema/manohara/segments/{slug}.json, and provenance from
// public/data/cinema/manohara/provenance.json. All three were generated by the
// work-specific importer scripts/import-manohara.mjs from the authoritative source
// repository (pugazg/kalaignar-cinema-works @ works/manohara) — see the source page.
//
// IMPORTANT terminology: the 1954 booklet prints NO numbered scenes. The 57 divisions
// are ARCHIVE-CREATED NAVIGATION SEGMENTS only, never "printed scene N". `sceneId`,
// `readerStructure: "scene"` and the `scene` folder name are internal identifiers,
// not a claim that the source is scene-numbered (`sourceSceneNumber` is always null).

// ── Segment index (index.json) ──────────────────────────────────────────────
export type ManoharaSegmentStub = {
  slug: string; // segment-001 … segment-057
  ordinal: number; // 1..57 (archive navigation order)
  sceneId: string; // manohara-s001 … (internal derivative id)
  readerLabelTa: string; // archive-derived setting label, e.g. "குகை உட்புறம்"
  startPdfPage: number;
  startPrintedPage: number;
  englishUnitCount: number;
};

export type ManoharaIndex = {
  workId: "manohara";
  titleTa: string;
  titleEn: string;
  shelf: "cinema-writing";
  readerStructure: "scene";
  segmentTerminology: "archival-navigation-segment";
  segmentCount: number; // 57
  sourceSceneNumbering: "none-printed";
  archivalSceneNumbering: "derivative-navigation-only";
  segments: ManoharaSegmentStub[];
};

// ── Per-segment content (segments/{slug}.json) ───────────────────────────────
// English unit kinds, exactly as produced by the source reader edition. Rendered as
// visually distinct blocks; text is never altered and null speaker labels stay null.
export type ManoharaUnitKind =
  | "dialogue"
  | "stage-direction"
  | "song-reference"
  | "chant"
  | "written-text";

export type ManoharaUnit = {
  id: string;
  kind: ManoharaUnitKind;
  speakerLabel: string | null; // exact source label (Tamil); null preserved verbatim
  text: string; // verbatim English derivative text (never normalized)
};

export type ManoharaPageProvenance = { pdf_page: number; printed_page: number };

export type ManoharaSegment = {
  workId: "manohara";
  slug: string;
  ordinal: number;
  sceneId: string;
  sourceSceneNumber: null; // always null — the booklet prints no scene numbers
  readerLabelTa: string;
  startPdfPage: number;
  startPrintedPage: number;
  canonicalPart: string;
  pageProvenance: ManoharaPageProvenance[];
  tamil: { text: string }; // verbatim Tamil scene derivative (rendered pre-wrap)
  english: { units: ManoharaUnit[] };
};

// ── Provenance manifest (provenance.json) ────────────────────────────────────
export type ManoharaProvenance = {
  workId: "manohara";
  sourceRepo: string;
  sourcePath: string;
  sourceCommit: string;
  buildVersion: number;
  source: {
    identifier: string;
    scan_sha256: string;
    pdf_pages: number;
    edition_statement_as_printed: string;
    publication_year_as_printed: number;
    rights_notice_as_printed: string;
    price_as_printed: string;
    publisher_name: string;
    printer_as_printed: string;
    credit_role: string;
    credit_name: string;
    main_text_pdf_pages: string;
    main_text_logical_printed_pages: string;
    ocr_authority: string;
  };
  sourceSceneNumbering: "none-printed";
  archivalSceneNumbering: "derivative-navigation-only";
  segmentCount: number;
  tamil: { sceneDerivatives: number; status: string };
  english: {
    edition: string;
    status: string;
    translationAuthority: string;
    translationUnits: number;
    unitKindCounts: Record<string, number>;
    immutableDialogueRecordsLinked: number;
    sourceUnlabelledSpokenUnits: number;
    crossPageUnits: number;
    songOccurrenceLinks: number;
    qaStatus: string;
  };
  integrity: {
    sourceScanSha256: string;
    translationInputAggregateSha256: string;
    validationInputAggregateSha256: string;
    readerEditionOutputs: Record<string, { sha256: string; bytes: number }>;
  };
  notes: string[];
};
