// Manohara (மனோகரா) — Kalaignar M. Karunanidhi's screenplay/dialogue booklet (1954).
//
// Digital Library Phase 2. Onboarded onto the shared library envelope with its own
// `scene` reader. Data-driven like the other Reading Rooms: the segment index is
// loaded from public/data/cinema/manohara/index.json, per-segment content is fetched
// from public/data/cinema/manohara/segments/{slug}.json, and provenance from
// public/data/cinema/manohara/provenance.json. All three were generated by the
// work-specific importer scripts/import-manohara.mjs from the authoritative source
// repository (pugazg/kalaignar-cinema-works @ works/manohara) — see the source page.
//
// IMPORTANT terminology: the 1954 booklet prints NO numbered scenes. The 57 divisions
// are ARCHIVE-CREATED NAVIGATION SEGMENTS only, never "printed scene N". `sceneId`,
// `readerStructure: "scene"` and the `scene` folder name are internal identifiers,
// not a claim that the source is scene-numbered (`sourceSceneNumber` is always null).

// ── Segment index (index.json) ──────────────────────────────────────────────
export type ManoharaSegmentStub = {
  slug: string; // segment-001 … segment-057
  ordinal: number; // 1..57 (archive navigation order)
  sceneId: string; // manohara-s001 … (internal derivative id)
  readerLabelTa: string; // archive-derived setting label, e.g. "குகை உட்புறம்"
  startPdfPage: number;
  startPrintedPage: number;
  englishUnitCount: number;
};

export type ManoharaIndex = {
  workId: "manohara";
  titleTa: string;
  titleEn: string;
  shelf: "cinema-writing";
  readerStructure: "scene";
  segmentTerminology: "archival-navigation-segment";
  segmentCount: number; // 57
  sourceSceneNumbering: "none-printed";
  archivalSceneNumbering: "derivative-navigation-only";
  segments: ManoharaSegmentStub[];
};

// ── Per-segment content (segments/{slug}.json) ───────────────────────────────
// English unit kinds, exactly as produced by the source reader edition. Rendered as
// visually distinct blocks; text is never altered and null speaker labels stay null.
export type ManoharaUnitKind =
  | "dialogue"
  | "stage-direction"
  | "song-reference"
  | "chant"
  | "written-text";

export type ManoharaPageProvenance = { pdf_page: number; printed_page: number };

// Structured source locator for units not linked to an immutable dialogue record
// (stage directions, song references, chants, written text, unlabelled utterances).
// Copied verbatim from the authoritative reader record; shape preserved.
export type ManoharaSourceLocator = {
  kind: string;
  ordinal: number;
  description: string;
};

// Per-unit archival provenance, copied DIRECTLY from the authoritative source reader
// record (works/manohara/editions/en/reader-edition.json → unit.source). None of these
// are reconstructed or converted into invented website IDs.
export type ManoharaUnitSource = {
  sourcePath: string; // e.g. works/manohara/dialogues/records/scene-001.json
  canonicalScenePath: string; // e.g. works/manohara/scenes/scene-001.md
  sourceRecordId: string | null; // immutable dialogue-record id (null for non-dialogue-linked units)
  sourceOccurrenceId: string | null; // song/performance occurrence id where present (e.g. manohara-song-001)
  sourceLocator: ManoharaSourceLocator | null; // structured locator where present; verbatim
  pageProvenance: ManoharaPageProvenance[]; // exact source page_provenance array
};

// One physical-page segment of an English unit that crosses a source page break.
// Present only when the authoritative translation record supplies it (the 17 cross-page units).
export type ManoharaEnglishPageSegment = {
  pdf_page: number;
  printed_page: number;
  english_text: string;
};

// English translation-layer metadata, copied directly from unit.translation. Editorial
// notes are retained verbatim as static metadata and are never altered or regenerated.
export type ManoharaUnitTranslation = {
  mode: string; // e.g. "prose-faithful"
  englishPageSegments?: ManoharaEnglishPageSegment[]; // only when the source supplies a cross-page split
  englishLines?: string[]; // only when the source represents the unit as discrete lines (not english_text)
  notes?: string[]; // authoritative editorial notes, verbatim; omitted when empty
};

export type ManoharaUnit = {
  id: string;
  kind: ManoharaUnitKind;
  speakerLabel: string | null; // exact source label (Tamil); null preserved verbatim
  text: string; // verbatim English derivative reading text (never normalized)
  source: ManoharaUnitSource; // archival source-linked audit trail (verbatim)
  translation: ManoharaUnitTranslation; // translation-layer metadata (verbatim)
};

export type ManoharaSegment = {
  workId: "manohara";
  slug: string;
  ordinal: number;
  sceneId: string;
  sourceSceneNumber: null; // always null — the booklet prints no scene numbers
  readerLabelTa: string;
  startPdfPage: number;
  startPrintedPage: number;
  canonicalPart: string;
  pageProvenance: ManoharaPageProvenance[];
  tamil: { text: string }; // verbatim Tamil scene derivative (rendered pre-wrap)
  english: { units: ManoharaUnit[] };
};

// ── Provenance manifest (provenance.json) ────────────────────────────────────
export type ManoharaProvenance = {
  workId: "manohara";
  sourceRepo: string;
  sourcePath: string;
  sourceCommit: string;
  buildVersion: number;
  source: {
    identifier: string;
    scan_sha256: string;
    pdf_pages: number;
    edition_statement_as_printed: string;
    publication_year_as_printed: number;
    rights_notice_as_printed: string;
    price_as_printed: string;
    publisher_name: string;
    printer_as_printed: string;
    credit_role: string;
    credit_name: string;
    main_text_pdf_pages: string;
    main_text_logical_printed_pages: string;
    ocr_authority: string;
  };
  sourceSceneNumbering: "none-printed";
  archivalSceneNumbering: "derivative-navigation-only";
  segmentCount: number;
  tamil: { sceneDerivatives: number; status: string };
  english: {
    edition: string;
    status: string;
    translationAuthority: string;
    translationUnits: number;
    unitKindCounts: Record<string, number>;
    immutableDialogueRecordsLinked: number;
    sourceUnlabelledSpokenUnits: number;
    crossPageUnits: number;
    songOccurrenceLinks: number;
    qaStatus: string;
  };
  integrity: {
    sourceScanSha256: string;
    translationInputAggregateSha256: string;
    validationInputAggregateSha256: string;
    readerEditionOutputs: Record<string, { sha256: string; bytes: number }>;
  };
  // Present project-level rights status of the UNDERLYING work authored by Kalaignar (Tamil:
  // நாட்டுடைமையாக்கப்பட்டது). This is a project-level provenance fact (Tamil Nadu Government
  // nationalisation) — deliberately NOT source-repo-derived, and kept DISTINCT from the 1954
  // edition's printed rights notice (source.rights_notice_as_printed). The GO's number and formal
  // ISSUE date are null until verified from the order itself; they are never invented or inferred.
  // The 2024-12-22 date is only the public HANDOVER of the GO, not its issue date.
  projectRights: {
    appliesTo: string; // the underlying Kalaignar-authored work only
    rightsStatus: string; // "nationalised-by-tamil-nadu-government"
    rightsAuthority: string; // "Government of Tamil Nadu"
    rightsAction: string; // "nationalisation"
    rightsAnnouncementDate: string; // "2024-08-22" (announced without royalty)
    governmentOrderNumber: string | null; // null until verified from the GO — never invented
    governmentOrderDate: string | null; // formal ISSUE date — null until verified (never inferred)
    governmentOrderHandoverDate: string | null; // "2024-12-22" public handover to Rajathi Ammal; NOT the issue date
    distinctionNote: string; // printed 1954 notice vs present nationalisation are different facts
    thirdPartyNote: string; // nationalisation does not extend to third-party contributions
    projectTranslationNote: string; // project-created English retains its own distinct provenance
    evidencePending: string; // exact GO number/issue date to be captured from an authoritative record
  };
  notes: string[];
};
