// Types and loaders for திருக்குறள் — கலைஞர் உரை.
//
// The single source of truth is public/data/thirukkural/, generated by scripts/import-thirukkural.mjs
// from the archive and verified by scripts/validate-thirukkural.mjs. Nothing here re-states a Kural,
// a title or a count: every value is read from that generated data at build time.

import fs from "node:fs";
import path from "node:path";

const DATA = path.join(process.cwd(), "public/data/thirukkural");

/** One couplet with Kalaignar's commentary on it, exactly as the edition sets them. */
export type ThirukkuralEntry = {
  number: number;
  paal: { index: number; tamil: string };
  iyal: { index: number; tamil: string };
  adhikaram: { number: number; tamil: string; from: number; to: number };
  /** The couplet's two printed lines. Always exactly two, and never joined into one. */
  tamilText: string[];
  kalaignarUrai: string;
  source: {
    /** The processing split the page was transcribed from — a transcription witness, not the
     *  controlling source. The controlling source is named only in provenance.json. */
    filename: string;
    role: string;
    scan: number;
    printedPage: string | null;
    pageType: string;
    record: string;
  };
  commentary: { author: string; edition: string | null };
};

export type ThirukkuralAdhikaram = {
  number: number;
  tamil: string;
  from: number;
  to: number;
  paal: { index: number; tamil: string };
  iyal: { index: number; tamil: string };
  kurals: ThirukkuralEntry[];
};

export type ThirukkuralIndexRow = {
  number: number;
  firstLine: string;
  paal: number;
  iyal: number;
  adhikaram: number;
};

export type ThirukkuralIndex = {
  workId: string;
  title: { ta: string; en: string };
  subtitle: { ta: string; en: string };
  poet: { ta: string; en: string };
  commentator: { ta: string; en: string };
  sourceRepo: string;
  sourcePath: string;
  sourceCommit: string;
  counts: { kurals: number; paal: number; iyal: number; adhikarams: number };
  paal: { index: number; tamil: string }[];
  iyal: { paal: number; index: number; tamil: string }[];
  adhikarams: {
    number: number; tamil: string; from: number; to: number;
    paal: { index: number; tamil: string };
    iyal: { index: number; tamil: string };
    file: string;
  }[];
  kurals: ThirukkuralIndexRow[];
};

export type ThirukkuralProvenance = {
  workId: string;
  sourceRepo: string;
  sourcePath: string;
  sourceCommit: string;
  controllingSource: {
    filename: string;
    sha256: string;
    byteSize: number;
    pageCount: number;
    committed: boolean;
    archiveIdentifier: string | null;
    repository: string | null;
  };
  identityStatus: string;
  identityVerification: { level: string; verifiedAgainst: string | null; verificationMethod: string | null };
  identitySourceNote: string;
  pageCorrespondence: { type: string; sourcePageEqualsArchiveScan: boolean } & Record<string, unknown>;
  edition: {
    statement: string | null;
    publisher: string | null;
    workTitleTa: string | null;
    workSubtitleTa: string | null;
    commentator: string | null;
  };
  derived: Record<string, unknown> & { commentaryPages: number; totalPageRecords: number };
  textualFidelity: string;
  transcriptionWitnesses: { note: string; declaredDerivedFiles: number; citedByKurals: number };
  excludedFromReadingBody: {
    rule: string;
    quotationsExcluded: number;
    quotationPageTypes: string[];
    quotationLedger: { kural: number; record: string; scan: number; pageType: string }[];
    note: string;
    alsoOutsideReadingBody: string[];
  };
};

const readJson = <T,>(p: string): T => JSON.parse(fs.readFileSync(p, "utf8")) as T;

export function loadThirukkuralIndex(): ThirukkuralIndex {
  return readJson<ThirukkuralIndex>(path.join(DATA, "index.json"));
}

export function loadThirukkuralProvenance(): ThirukkuralProvenance {
  return readJson<ThirukkuralProvenance>(path.join(DATA, "provenance.json"));
}

/** Loads a single அதிகாரம் — ten Kurals — so no page ever pulls the whole edition into memory. */
export function loadAdhikaram(n: number): ThirukkuralAdhikaram | null {
  const file = path.join(DATA, "adhikarams", `${String(n).padStart(3, "0")}.json`);
  if (!Number.isInteger(n) || !fs.existsSync(file)) return null;
  return readJson<ThirukkuralAdhikaram>(file);
}

/** Resolves one Kural by loading only the அதிகாரம் that contains it. */
export function loadKural(n: number): { entry: ThirukkuralEntry; adhikaram: ThirukkuralAdhikaram } | null {
  if (!Number.isInteger(n)) return null;
  const index = loadThirukkuralIndex();
  const owner = index.adhikarams.find((a) => n >= a.from && n <= a.to);
  if (!owner) return null;
  const adhikaram = loadAdhikaram(owner.number);
  const entry = adhikaram?.kurals.find((k) => k.number === n);
  return adhikaram && entry ? { entry, adhikaram } : null;
}
