/**
 * Wave 7 — Batch 1 P3 route-manifest generator.
 *
 *   npx tsx --tsconfig tsconfig.scripts.json scripts/build-wave7-b1-p3-routes.ts
 *
 * Emits data/internal/wave7/b1-p3-routes.json — the exact set of direct /cinema routes the three
 * Batch-1 works add at P3: per work a landing, one section route PER SCENE (derived from the frozen
 * payload via the SAME section-slug authority the app's generateStaticParams uses — never a
 * reconstructed 1..N range), and a source route. The record is discoverable:false / sitemapExposed:false:
 * the routes are prerendered but stay absent from LIBRARY_WORKS, /read and the sitemap until P4.
 * Generated; do not hand-edit — re-run this generator.
 */
import fs from "node:fs";
import path from "node:path";
import { loadWave7Cinema, WAVE7_CINEMA_SLUGS } from "../data/wave7-cinema";
import { wave7CinemaSectionSlugs } from "../lib/cinema-wave7-routes";

const root = process.cwd();
const works = WAVE7_CINEMA_SLUGS.map((slug) => {
  const w = loadWave7Cinema(slug);
  if (!w) { console.error(`build-wave7-b1-p3-routes: payload for ${slug} unreadable`); process.exit(1); }
  const sections = wave7CinemaSectionSlugs(slug);
  const routes = [
    `/cinema/${slug}`,
    ...sections.map((s) => `/cinema/${slug}/${s}`),
    `/cinema/${slug}/source`,
  ];
  return {
    slug, titleTa: w.titleTa, titleEn: w.titleEn,
    sceneCount: w.scenes.length, sectionRouteCount: sections.length,
    routeCount: routes.length, // landing + sections + source
    routes,
  };
});

const allRoutes = works.flatMap((w) => w.routes);
if (new Set(allRoutes).size !== allRoutes.length) { console.error("build-wave7-b1-p3-routes: duplicate route across works"); process.exit(1); }

const manifest = {
  note:
    "Wave 7 Batch 1 P3 route record — direct /cinema reader/section/source routes for the three Batch-1 " +
    "cinema works, prerendered but UNDISCOVERED (absent from LIBRARY_WORKS, /read discovery and the sitemap) " +
    "until Batch 1 P4. Section routes are derived per-scene from the frozen vendored payloads via " +
    "lib/cinema-wave7-routes.ts (never a reconstructed 1..N range). Generated by " +
    "scripts/build-wave7-b1-p3-routes.ts; do not hand-edit.",
  wave: 7,
  batch: 1,
  batchId: "b1-cinema",
  readerFamily: "cinema-scene",
  discoverable: false,
  sitemapExposed: false,
  workCount: works.length,
  totalRouteCount: allRoutes.length,
  // Exact build delta introduced by P3, measured from `npm run build` at the P3 tip. Each route is one
  // statically prerendered page, so prerender and .html both grow by totalRouteCount. Baseline is the P1
  // hidden-boundary build (data/internal/wave7 P1 authority / validate-wave7-b1-p1.ts): 3918 / 3913.
  buildDelta: {
    baseline: { prerenderRoutes: 3918, html: 3913 },
    added: allRoutes.length,
    afterP3: { prerenderRoutes: 3918 + allRoutes.length, html: 3913 + allRoutes.length },
  },
  works,
};

const out = path.join(root, "data/internal/wave7/b1-p3-routes.json");
fs.writeFileSync(out, JSON.stringify(manifest, null, 2) + "\n");
console.log(`build-wave7-b1-p3-routes: wrote ${out}`);
console.log(`  ${works.length} works · ${allRoutes.length} total routes (` + works.map((w) => `${w.slug} ${w.routeCount}`).join(", ") + ")");
