/**
 * Wave 7 Batches 2-4 P3 route-manifest generator.
 *
 *   npx tsx --tsconfig tsconfig.scripts.json scripts/build-wave7-b2-b4-p3-routes.ts
 *
 * Emits data/internal/wave7/b2-b4-p3-routes.json — the exact direct routes the 13 works add at P3,
 * DERIVED from the frozen P1 payloads (drama play.json.readingUnits, novel adapted sections, essay
 * publication.json.articles) — never a reconstructed 1..N range. Per work: a landing, a source route, and
 * one child route per reading unit. The works stay discoverable:false / sitemapExposed:false until P4.
 */
import fs from "node:fs";
import path from "node:path";
import { WAVE7_DRAMA_SLUGS } from "../lib/drama-wave7-routes";
import { WAVE7_NOVEL_SLUGS } from "../lib/novels-wave7-routes";
import { WAVE7_ESSAY_SLUGS } from "../lib/essays-wave7-routes";
import { wave7NovelToNovel } from "../lib/wave7-novels-adapter";

const root = process.cwd();
const load = (p: string) => JSON.parse(fs.readFileSync(path.join(root, p), "utf8"));

function dramaRoutes(slug: string): string[] {
  const play = load(`public/data/plays/${slug}/play.json`);
  return [`/plays/${slug}`, `/plays/${slug}/source`, ...play.readingUnits.map((u: { slug: string }) => `/plays/${slug}/${u.slug}`)];
}
function novelRoutes(slug: string): string[] {
  const novel = wave7NovelToNovel(load(`public/data/novels/${slug}/novel.json`));
  return [`/novels/${slug}`, `/novels/${slug}/source`, ...novel.sections.map((s) => `/novels/${slug}/${s.slug}`)];
}
function essayRoutes(slug: string): string[] {
  const pub = load(`public/data/essays/${slug}/publication.json`);
  return [`/essays/${slug}`, `/essays/${slug}/source`, ...pub.articles.map((a: { slug: string }) => `/essays/${slug}/articles/${a.slug}`)];
}

const shelves = [
  { batch: 2, shelf: "drama", family: "plays", slugs: WAVE7_DRAMA_SLUGS, routesOf: dramaRoutes },
  { batch: 3, shelf: "fiction", family: "novels", slugs: WAVE7_NOVEL_SLUGS, routesOf: novelRoutes },
  { batch: 4, shelf: "essays-articles", family: "essays", slugs: WAVE7_ESSAY_SLUGS, routesOf: essayRoutes },
];

const works: { slug: string; batch: number; shelf: string; landing: string; source: string; childRouteCount: number; routeCount: number; routes: string[] }[] = [];
for (const sh of shelves) {
  for (const slug of sh.slugs) {
    const routes = sh.routesOf(slug);
    works.push({ slug, batch: sh.batch, shelf: sh.shelf, landing: `/${sh.family}/${slug}`, source: `/${sh.family}/${slug}/source`, childRouteCount: routes.length - 2, routeCount: routes.length, routes });
  }
}
const all = works.flatMap((w) => w.routes);
if (new Set(all).size !== all.length) { console.error("duplicate route across works"); process.exit(1); }
const byBatch = (b: number) => works.filter((w) => w.batch === b).reduce((n, w) => n + w.routeCount, 0);

const manifest = {
  note: "Wave 7 Batches 2-4 P3 route record — direct reader/child/source routes for the 13 works (2 Drama + 5 Novels + 6 Essays), prerendered but UNDISCOVERED (absent from LIBRARY_WORKS, /read discovery and the sitemap) until P4. Child routes are derived per reading unit from the frozen P1 payloads (drama readingUnits, novel adapted sections, essay articles) via each shelf's Wave-7 registry — never a reconstructed 1..N range. Generated by scripts/build-wave7-b2-b4-p3-routes.ts; do not hand-edit.",
  wave: 7, batches: [2, 3, 4], discoverable: false, sitemapExposed: false,
  workCount: works.length, totalRouteCount: all.length,
  routeCountByBatch: { drama: byBatch(2), novels: byBatch(3), essays: byBatch(4) },
  buildDelta: { baseline: { prerenderRoutes: 4051, html: 4046 }, added: all.length, afterP3: { prerenderRoutes: 4051 + all.length, html: 4046 + all.length } },
  works,
};
const out = path.join(root, "data/internal/wave7/b2-b4-p3-routes.json");
fs.writeFileSync(out, JSON.stringify(manifest, null, 2) + "\n");
console.log(`build-wave7-b2-b4-p3-routes: wrote ${out}`);
console.log(`  ${works.length} works · ${all.length} routes (drama ${byBatch(2)} + novels ${byBatch(3)} + essays ${byBatch(4)})`);
