// Wave 8 P1 — hidden data foundation (Murasoli 42–47 · ஒரே முத்தம் · சங்கத் தமிழ்).
//
//   node scripts/import-wave8.mjs <murasoli-letters clone> <stage-plays clone> <literary-commentary clone> [--verify]
//
// Every clone must sit at its FROZEN Wave-8 P0 commit with every scoped subtree at its frozen tree id (fail closed).
// Output is INTERNAL ONLY — `data/internal/wave8/` — never under `public/`, so no generic reader can route it. Nothing
// here touches the catalogue, discovery, sitemap, route registries or the live Murasoli Vols 48–54 payloads.
// Deterministic: no clocks, no randomness; a rerun is byte-identical. `--verify` regenerates in memory and fails
// unless every committed file (and the manifest) is byte-identical to the regeneration.
import fs from "node:fs";
import path from "node:path";
import { WAVE8_PINS, assertPinned, emit, toJson, sha256 } from "./wave8/common.mjs";
import { importMurasoli, murasoliFiles } from "./wave8/murasoli.mjs";
import { importOreMutham, oreMuthamFiles } from "./wave8/ore-mutham.mjs";
import { importSangatamil, sangatamilFiles } from "./wave8/sangatamil.mjs";

const args = process.argv.slice(2).filter((a) => !a.startsWith("--"));
const VERIFY = process.argv.includes("--verify");
if (args.length !== 3) { console.error("usage: node scripts/import-wave8.mjs <murasoli-letters> <stage-plays> <literary-commentary> [--verify]"); process.exit(2); }
const [MURASOLI, STAGE, LIT] = args;
const ROOT = process.cwd();
const OUT = "data/internal/wave8";

// ── Frozen source boundary ───────────────────────────────────────────────────────────────────────
const P = WAVE8_PINS;
assertPinned(MURASOLI, P.murasoli, Object.fromEntries(Object.entries(P.murasoli.volumes).map(([v, t]) => [`volumes/volume-${v}`, t])));
assertPinned(STAGE, P.oreMutham, { [P.oreMutham.workPath]: P.oreMutham.workTree });
assertPinned(LIT, P.sangatamil, { [P.sangatamil.workPath]: P.sangatamil.workTree });

// ── Import ───────────────────────────────────────────────────────────────────────────────────────
const volumes = importMurasoli(MURASOLI);
const ore = importOreMutham(STAGE);
const sanga = importSangatamil(LIT);
const files = { ...murasoliFiles(volumes), ...oreMuthamFiles(ore), ...sangatamilFiles(sanga) };

const mismatches = [];
const inventory = [];
for (const rel of Object.keys(files).sort()) {
  const content = files[rel];
  inventory.push({ path: `${OUT}/${rel}`, sha256: emit(ROOT, `${OUT}/${rel}`, content, { verify: VERIFY, mismatches }), bytes: Buffer.byteLength(content) });
}

// ── Master manifest ──────────────────────────────────────────────────────────────────────────────
const letters = volumes.flatMap((v) => v.letters);
const qualified = letters.filter((l) => l.qualification);
const pageStatus = (field) => sanga.pages.reduce((a, p) => { const k = field(p); a[k] = (a[k] ?? 0) + 1; return a; }, {});
const manifest = {
  schema: 1,
  note: "INTERNAL — Wave 8 P1 hidden data foundation (never served). Generated by scripts/import-wave8.mjs from the frozen Wave-8 P0 source pins; no public surface changes at P1.",
  stage: "P1",
  controlAuthority: { repo: "pugazg/kalaignar-tribute", census: "projects/kalaignar-digital-library/WAVE8_COMPLETED_WORKS_CENSUS.md", p0FrozenBy: "PR #37 merge cc99ebb6a2c35130a6b42ac2051f7907fbc9129c" },
  implementationBaseAtP1: { sha: "cf769d06c1bdb4abc58b5ef2c26e609a777b4923", tree: "35d64fb97f7bed1e26c3bb09fea5649db9d1e348" },
  accounting: { sourcePublicationInputs: 8, newCanonicalLibraryWorks: 2, existingWorkExpanded: "murasoli-letters (volume-level expansion, catalogue delta 0)", projectedCatalogueAfterPublication: 335 },
  sources: {
    murasoli: { repo: P.murasoli.repo, commit: P.murasoli.commit, repoTree: P.murasoli.repoTree, volumes: Object.fromEntries(volumes.map((v) => [v.volume, { path: v.sourcePath, tree: v.sourceTree }])) },
    oreMutham: { repo: P.oreMutham.repo, commit: P.oreMutham.commit, repoTree: P.oreMutham.repoTree, path: P.oreMutham.workPath, tree: P.oreMutham.workTree },
    sangatamil: { repo: P.sangatamil.repo, commit: P.sangatamil.commit, repoTree: P.sangatamil.repoTree, path: P.sangatamil.workPath, tree: P.sangatamil.workTree },
  },
  segments: {
    B1_murasoli: {
      libraryWork: "murasoli-letters",
      catalogueEffect: 0,
      volumes: volumes.map((v) => ({
        volume: v.volume,
        classification: v.letters.some((l) => l.qualification) ? "READY WITH QUALIFICATION" : "READY",
        tamilRecords: v.letters.length,
        englishRecords: v.letters.filter((l) => l.english.text).length,
        controllingSource: v.controllingSource,
        ...(v.sourceObservations ? { sourceObservations: v.sourceObservations } : {}),
      })),
      totals: { tamil: letters.length, english: letters.filter((l) => l.english.text).length, uniqueIds: new Set(letters.map((l) => l.id)).size, uniqueRouteSlugs: new Set(letters.map((l) => l.routeSlug)).size },
      idPolicy: {
        canonicalId: "m{volume}-{source chapter file stem} — source-derived, rerun-stable, never positional, never a corrected number",
        printedNumber: "carried separately and exactly as printed (never suffixed, never renumbered)",
        routeSlug: "m{volume}-l{printedNumber} where that pair is unique in its volume (the live Vols 48–54 convention); otherwise m{volume}-l{source chapter file stem}",
        sourceNumberingFacts: ["Vol 42 prints 3154 between 3376 and 3378; no 3377 exists", "Vol 46 prints 3637 twice (two distinct letters); no 3636; no 3644–3646", "3647–3649 occur independently in Vols 46 and 47"],
      },
      qualifications: qualified.map((l) => ({ id: l.id, volume: l.volume, printedNumber: l.printedNumber, ...l.qualification })),
    },
    B2_oreMutham: {
      libraryWork: "ore-mutham (NEW — not yet catalogued)",
      catalogueEffect: 1,
      classification: "READY",
      pages: ore.verification.pageRecords, pageStatus: ore.verification.pageStatus, blocked: ore.verification.blocked, needsReview: ore.verification.needsReview,
      parts: ore.parts.map(({ id, headingTa, headingEn, unitCount, printedNumbers }) => ({ id, headingTa, headingEn, unitCount, printedNumbers })),
      units: ore.units.length,
      readerFamily: "stage-play (additive PlayPart / PlayReadingUnit.partId in data/plays.ts)",
    },
    B3_sangatamil: {
      libraryWork: "sangatamil (NEW — not yet catalogued)",
      catalogueEffect: 1,
      classification: "READY WITH QUALIFICATION",
      scans: sanga.pages.length,
      tamilStatus: pageStatus((p) => p.tamilStatus),
      englishStatus: pageStatus((p) => p.english.status),
      sourceLimitedScans: sanga.pages.filter((p) => p.sourceLimitation).map((p) => p.scan),
      sections: sanga.sections.length,
      formalProvenanceUnits: sanga.citations.filter((c) => c.kind === "formal-citation").length,
      sourceNoteOnlyRecords: sanga.citations.filter((c) => c.kind === "source-note").length,
      provenanceLocatedBy: sanga.citations.reduce((a, c) => { a[c.locatedBy] = (a[c.locatedBy] ?? 0) + 1; return a; }, {}),
      pageTypes: pageStatus((p) => p.pageType),
      readerFamily: "commentary-unit (see data/internal/wave8/p1-architecture-decisions.json)",
    },
  },
  artifacts: inventory,
};
const manifestRel = `${OUT}/wave8-p1-manifest.json`;
emit(ROOT, manifestRel, toJson(manifest), { verify: VERIFY, mismatches });

if (VERIFY) {
  if (mismatches.length) { console.error(`import-wave8 --verify: NOT byte-identical:\n  ${mismatches.join("\n  ")}`); process.exit(1); }
  console.log(`import-wave8 --verify: ${inventory.length} artifacts + manifest byte-identical to a fresh regeneration from the frozen pins`);
} else {
  console.log(`import-wave8 — wrote ${inventory.length} artifacts + manifest under ${OUT}/`);
}
console.log(`  B1 Murasoli 42–47: ${letters.length} Tamil / ${letters.filter((l) => l.english.text).length} English · ${qualified.length} qualified (${qualified.map((l) => l.printedNumber).join(", ")})`);
console.log(`  B2 ஒரே முத்தம்: ${ore.units.length} units (${ore.parts.map((p) => `${p.id} ${p.unitCount}`).join(" + ")}) · pages ${JSON.stringify(ore.verification.pageStatus)}`);
console.log(`  B3 சங்கத் தமிழ்: ${sanga.pages.length} scans · ${sanga.sections.length} sections · ${sanga.citations.length} provenance records · Tamil ${JSON.stringify(manifest.segments.B3_sangatamil.tamilStatus)}`);
